refactor: Entire Project refactored. Added Knockback pickup functionality, added config option for applying knockdown on bleeding

diff --git a/.github/workflows/upload-to-modrinth.yml b/.github/workflows/upload-to-modrinth.yml
--- a/.github/workflows/upload-to-modrinth.yml
+++ b/.github/workflows/upload-to-modrinth.yml
@@ -10,59 +10,66 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check tag format
-      run: |
-        TAG_NAME=${GITHUB_REF#refs/tags/}
-        if ! [[ $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(PATCH|MINOR|MAJOR)-(release|alpha|beta)$ ]]; then
-          echo "Invalid tag format: $TAG_NAME"
-          exit 1
-        fi
+      - name: Check tag format
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+          if ! [[ $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(PATCH|MINOR|MAJOR)-(release|alpha|beta)$ ]]; then
+            echo "Invalid tag format: $TAG_NAME"
+            exit 1
+          fi
 
-    - name: Checkout repository
-      uses: actions/checkout@v4
-      with:
-        ref: ${{ github.head_ref }}
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
 
-    - name: Set up JDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: 'adopt'
-        java-version: '8'
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'adopt'
+          java-version: '8'
 
-    - name: Extract tag information
-      id: tag_info
-      run: |
-        TAG_INFO=($(echo $GITHUB_REF | sed 's|refs/tags/||' | tr '-' ' '))
-        echo "VERSION_TYPE=${TAG_INFO[2]}" >> $GITHUB_ENV
-        echo "CHANGELOG_TYPE=${TAG_INFO[1]}" >> $GITHUB_ENV
+      - name: Extract tag information
+        id: tag_info
+        run: |
+          TAG_INFO=($(echo $GITHUB_REF | sed 's|refs/tags/||' | tr '-' ' '))
+          echo "VERSION_TYPE=${TAG_INFO[2]}" >> $GITHUB_ENV
+          echo "CHANGELOG_TYPE=${TAG_INFO[1]}" >> $GITHUB_ENV
+          
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          echo "CHANGELOG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
 
-        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-        echo "CHANGELOG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
+      - name: Get dependencies
+        run: |
+          echo We are in path $(pwd)
+          cd libs
+          curl -Lo libs/creative-core-1.16.5.jar https://www.curseforge.com/api/v1/mods/257814/files/3419983/download
+          curl -Lo libs/player-revive-1.16.5.jar https://www.curseforge.com/api/v1/mods/266890/files/3419960/download
+          cd ..
 
-    - name: Get dependencies
-      run: |
-        cd libs
-        curl -Lo libs/creative-core-1.16.5.jar https://www.curseforge.com/api/v1/mods/257814/files/3419983/download
-        curl -Lo libs/player-revive-1.16.5.jar https://www.curseforge.com/api/v1/mods/266890/files/3419960/download
-        cd ..
+      - name: Run ./gradlew updateInformation
+        run: |
+          ./gradlew updateInformation
+        env:
+          VERSION_TYPE: ${{ env.VERSION_TYPE }}
+          CHANGELOG_MESSAGE: ${{ env.CHANGELOG_MESSAGE }}
+          CHANGELOG_TYPE: ${{ env.CHANGELOG_TYPE }}
 
-    - name: Run ./gradlew updateInformation
-      run: |
-        ./gradlew updateInformation
-      env:
-        VERSION_TYPE: ${{ env.VERSION_TYPE }}
-        CHANGELOG_MESSAGE: ${{ env.CHANGELOG_MESSAGE }}
-        CHANGELOG_TYPE: ${{ env.CHANGELOG_TYPE }}
+      - uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          branch: main
+          commit_message: "chore: Update release files"
+          commit_user_name: "Dominik Rathmer"
+          commit_user_email: "rathmerdominik@outlook.de"
 
-    - uses: stefanzweifel/git-auto-commit-action@v5
-      with:
-        branch: main
-        commit_message: "chore: Update release files"
-        commit_user_name: "Dominik Rathmer"
-        commit_user_email: "rathmerdominik@outlook.de"
+      - name: Run ./gradlew modrinth
+        run: |
+          ./gradlew modrinth
+        env:
+          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
 
-    - name: Run ./gradlew modrinth
-      run: |
-        ./gradlew modrinth
-      env:
-        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
+      - name: Run ./gradlew publishCurseForge
+        run: |
+          ./gradlew publishCurseForge
+        env:
+          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
